#!/usr/bin/env python3
"""
Monthly CPI update script.

Run after BLS publishes new CPI data. Workflow:
  1. Re-runs build_us_cpi.py to fetch the latest raw index data from BLS API.
  2. Appends the new month column to US_CPI and US_CPI_Weights sheets in FINAL.xlsx
     (extends row 5 date headers + row 6+ data — never deletes existing dates/data).
  3. Writes the new month label to Tabela cell D3 only; E3:I3 update via their formulas.
  4. Computes MoM / MM3MA / MM6MA / YoY in Python and fills the Tabela data rows.
  5. Generates cpi_table.html for GitHub Pages.
  6. Commits and pushes to GitHub.

Usage:
    cd C:\\Users\\rodri\\us-cpi
    python update_cpi.py
"""

import os, sys, subprocess, statistics, calendar
from datetime import date
from pathlib import Path
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_DIR   = Path(__file__).parent.resolve()
SOURCE_XLS = REPO_DIR / "US_CPI.xlsx"          # generated by build_us_cpi.py
FINAL_XLS  = Path(r"C:\Users\rodri\CPI\US_CPI_FINAL.xlsx")
HTML_OUT   = REPO_DIR / "cpi_table.html"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def match_name(target, source_cats):
    """Prefix-match category names, returning shortest candidate."""
    t = target.strip().lower()
    for c in source_cats:
        if c.strip().lower() == t:
            return c
    candidates = [c for c in source_cats if c.strip().lower().startswith(t)]
    return min(candidates, key=len) if candidates else None


_MONTH_ABBR = {m.lower(): i for i, m in enumerate(calendar.month_abbr) if m}

def _label_to_date(label):
    """'Apr-26' → date(2026, 4, 1). Day is always 1."""
    mon_str, yr_str = label.split("-")
    mon = _MONTH_ABBR[mon_str.lower()]
    yr  = int(yr_str)
    yr  = yr + 2000 if yr < 100 else yr
    return date(yr, mon, 1)


def _col_to_label(col_idx, ws_raw):
    """Return the Mon-YY header label for a 1-indexed column."""
    v = ws_raw.cell(5, col_idx).value
    return v if v else f"col{col_idx}"


def _last_date_col(ws):
    """Find rightmost column in row 5 that has a non-None value."""
    for c in range(ws.max_column, 3, -1):
        if ws.cell(5, c).value is not None:
            return c
    return 3


def _build_cat_to_row(ws, min_row=6, cat_col=3):
    """Map category name → first row number in ws (raw data rows only — first occurrence wins)."""
    result = {}
    for r in range(min_row, ws.max_row + 1):
        cat = ws.cell(r, cat_col).value
        if cat is not None:
            key = str(cat).strip()
            if key not in result:
                result[key] = r
    return result


# Formula blocks in US_CPI sheet of FINAL.xlsx (extended each new month via Translator)
FORMULA_BLOCKS = [
    (392,  774),   # block 1 (intermediate)
    (778,  1160),  # MoM (%) — source for Tabela
    (1163, 1545),  # MM3MA   — source for Tabela
    (1549, 1931),  # MM6MA   — source for Tabela
    (1935, 2317),  # YoY     — source for Tabela
]

# Row ranges to READ from FINAL.xlsx US_CPI (data_only=True) for each variation type
VARIATION_READ_BLOCKS = {
    "MoM":   (392,  774),
    "MM3MA": (1163, 1545),
    "MM6MA": (1549, 1931),
    "YoY":   (1935, 2317),
}


def _last_formula_col(ws):
    """Return the rightmost column that has content in the first row of any formula block. 0 = none found."""
    max_col = 0
    for first_row, _ in FORMULA_BLOCKS:
        for c in range(ws.max_column, 3, -1):
            if ws.cell(first_row, c).value is not None:
                if c > max_col:
                    max_col = c
                break
    return max_col


def read_variation_block(ws_do, row_start, row_end, max_col):
    """
    Read cached formula values from a US_CPI variation block (data_only workbook).
    Returns {category: {col_idx: float}} — only columns with numeric cached values.
    """
    result = {}
    for row in ws_do.iter_rows(min_row=row_start, max_row=row_end,
                                min_col=3, max_col=max_col, values_only=True):
        cat = row[0]
        if cat is None:
            continue
        row_data = {}
        for i, v in enumerate(row[1:], start=4):
            if isinstance(v, (int, float)):
                row_data[i] = v
        if row_data:
            result[str(cat).strip()] = row_data
    return result


def _merge_variations(python_var, excel_var):
    """
    Merge Excel formula block values with Python-computed values.
    Excel values take priority (authoritative for cached months).
    Python fills columns not yet cached in Excel (the new month just added).
    """
    merged = {}
    for block in ["MoM", "MM3MA", "MM6MA", "YoY"]:
        m = {}
        py_b = python_var.get(block, {})
        ex_b = excel_var.get(block, {})
        for cat in set(py_b) | set(ex_b):
            combined = dict(py_b.get(cat, {}))
            combined.update(ex_b.get(cat, {}))  # Excel overrides where cached
            m[cat] = combined
        merged[block] = m
    return merged


def _excel_recalculate(xls_path):
    """
    Open xls_path in Excel (COM), force recalculation of all formulas, save, close.
    Restores the formula cache that openpyxl clears on every save.
    Safe to call when other Excel files are already open (only quits if we launched Excel).
    """
    try:
        import win32com.client
        try:
            excel = win32com.client.GetActiveObject("Excel.Application")
            launched = False
        except Exception:
            excel = win32com.client.Dispatch("Excel.Application")
            launched = True

        excel.Visible = False
        excel.DisplayAlerts = False
        wb = excel.Workbooks.Open(str(xls_path.resolve()))
        excel.Calculate()
        wb.Save()
        wb.Close(False)
        if launched:
            excel.Quit()
        print("  Formula cache refreshed via Excel.")
    except Exception as exc:
        print(f"  Warning: Excel recalculation skipped ({exc}) — Python fallback used.")


def _extend_and_recalculate(xls_path, formula_lc=0, new_cols=None):
    """
    Extend formula blocks via Excel COM AutoFill (if new_cols given), then recalculate.
    Called after openpyxl save. More reliable than openpyxl Translator for complex formulas.
    """
    try:
        import win32com.client
        try:
            excel = win32com.client.GetActiveObject("Excel.Application")
            launched = False
        except Exception:
            excel = win32com.client.Dispatch("Excel.Application")
            launched = True

        excel.Visible = False
        excel.DisplayAlerts = False
        wb = excel.Workbooks.Open(str(xls_path.resolve()))

        if new_cols:
            ws = wb.Sheets("US_CPI")
            last_new = max(new_cols)
            for first_row, last_row in FORMULA_BLOCKS:
                src_rng  = ws.Range(ws.Cells(first_row, formula_lc),
                                    ws.Cells(last_row,  formula_lc))
                fill_rng = ws.Range(ws.Cells(first_row, formula_lc),
                                    ws.Cells(last_row,  last_new))
                src_rng.AutoFill(fill_rng, 0)  # xlFillDefault = 0
            print(f"  Formula blocks extended to col {last_new} via Excel COM.")

        excel.Calculate()
        wb.Save()
        wb.Close(False)
        if launched:
            excel.Quit()
        print("  Formula cache refreshed via Excel.")
    except Exception as exc:
        print(f"  Warning: Excel COM operation skipped ({exc}) — Python fallback used.")


# ---------------------------------------------------------------------------
# Step 1 – fetch fresh raw data
# ---------------------------------------------------------------------------

def rebuild_source():
    print("=== Running build_us_cpi.py ===")
    result = subprocess.run(
        [sys.executable, str(REPO_DIR / "build_us_cpi.py")],
        cwd=str(REPO_DIR)
    )
    if result.returncode != 0:
        print("ERROR: build_us_cpi.py failed.")
        sys.exit(1)
    print("build_us_cpi.py done.\n")


# ---------------------------------------------------------------------------
# Step 2 – append new month columns to FINAL.xlsx raw sheets
# ---------------------------------------------------------------------------

def copy_new_months_to_final(ws_src_raw, ws_src_wts, ws_final_raw, ws_final_wts):
    """
    Appends any new month columns from SOURCE into FINAL's US_CPI and
    US_CPI_Weights sheets. Never overwrites existing data — only extends.

    Row 5        = date headers
    Rows 6–391   = raw index / weight values (matched by category name, first occurrence)
    Rows 392+    = formula blocks — extended via COM AutoFill after save (never overwritten with values)
    """
    final_lc = _last_date_col(ws_final_raw)
    src_lc   = _last_date_col(ws_src_raw)

    # --- raw data + weights ---
    if src_lc > final_lc:
        new_cols = list(range(final_lc + 1, src_lc + 1))
        print(f"  Appending {len(new_cols)} new month(s) to FINAL: col {new_cols[0]}..{new_cols[-1]}")

        # extend date headers in row 5
        for c in new_cols:
            ws_final_raw.cell(5, c).value = ws_src_raw.cell(5, c).value
            ws_final_wts.cell(5, c).value = (ws_src_wts.cell(5, c).value
                                              or ws_src_raw.cell(5, c).value)

        # append raw index values — first occurrence maps to raw data rows (6–391)
        final_rows = _build_cat_to_row(ws_final_raw)
        for r_src in range(6, ws_src_raw.max_row + 1):
            cat = ws_src_raw.cell(r_src, 3).value
            if cat is None:
                continue
            r_fin = final_rows.get(str(cat).strip())
            if r_fin is None:
                continue
            for c in new_cols:
                ws_final_raw.cell(r_fin, c).value = ws_src_raw.cell(r_src, c).value

        # append weight values
        final_wt_rows = _build_cat_to_row(ws_final_wts)
        for r_src in range(6, ws_src_wts.max_row + 1):
            cat = ws_src_wts.cell(r_src, 3).value
            if cat is None:
                continue
            r_fin = final_wt_rows.get(str(cat).strip())
            if r_fin is None:
                continue
            for c in new_cols:
                ws_final_wts.cell(r_fin, c).value = ws_src_wts.cell(r_src, c).value
    else:
        print(f"  FINAL raw data already current (last col = {final_lc})")

    # --- formula blocks (detected here; extended via COM AutoFill after save) ---
    formula_lc = _last_formula_col(ws_final_raw)
    new_formula_cols = []
    if formula_lc == 0:
        print("  No formula blocks found in FINAL — skipping formula extension")
    elif formula_lc < src_lc:
        new_formula_cols = list(range(formula_lc + 1, src_lc + 1))
        print(f"  Formula blocks will be extended: col {new_formula_cols[0]}..{new_formula_cols[-1]} (via Excel COM)")
    else:
        print(f"  Formula blocks already current (last col = {formula_lc})")
    return formula_lc, new_formula_cols


# ---------------------------------------------------------------------------
# Step 3 – compute variations from raw index data
# ---------------------------------------------------------------------------

def load_raw(ws_raw):
    """
    Returns raw[cat_name] = {col_idx(1-based): float}.
    Cols 4+ = months; row 5 = date headers; rows 6+ = categories.
    """
    raw = {}
    for row in ws_raw.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        entry = {}
        for i, v in enumerate(row[3:], start=4):
            if isinstance(v, (int, float)):
                entry[i] = v
        if entry:
            raw[cat] = entry
    return raw


def compute_mom(raw):
    mom = {}
    for cat, cols_d in raw.items():
        cols = sorted(cols_d.keys())
        m = {}
        for i in range(1, len(cols)):
            c, p = cols[i], cols[i - 1]
            cur, prv = cols_d[c], cols_d[p]
            if prv and prv != 0:
                m[c] = (cur / prv - 1) * 100
        mom[cat] = m
    return mom


def compute_mma(mom, window):
    result = {}
    for cat, m in mom.items():
        cols = sorted(m.keys())
        r = {}
        for i in range(window - 1, len(cols)):
            vals = [m[cols[i - j]] for j in range(window)]
            if all(isinstance(v, float) for v in vals):
                r[cols[i]] = sum(vals) / window
        result[cat] = r
    return result


def compute_yoy(raw):
    yoy = {}
    for cat, cols_d in raw.items():
        y = {}
        for c, cur in cols_d.items():
            prv_c = c - 12
            if prv_c in cols_d:
                prv = cols_d[prv_c]
                if prv and prv != 0:
                    y[c] = (cur / prv - 1) * 100
        yoy[cat] = y
    return yoy


def last_col(raw):
    return max(max(d.keys()) for d in raw.values() if d)


# ---------------------------------------------------------------------------
# Step 4 – fill Tabela sheet
# ---------------------------------------------------------------------------

NUM_FMT = "0.00"

SECTIONS = [
    (3,   4,   43,  "MoM"),
    (45,  46,  85,  "MM3MA"),
    (87,  88,  127, "MM6MA"),
    (129, 130, 169, "YoY"),
]


def fill_tabela(ws_tabela, ws_weights, variations, last_c):
    """
    variations = {"MoM": {cat: {col: val}}, "MM3MA": ..., ...}
    last_c     = 1-based column index of the most recent month.

    Writes only data cells (cols C-K in rows 4-169). Header rows and month
    label cells in row 3 are NOT touched here — D3 is written in main().
    """
    DATE_COLS = [last_c - i for i in range(6)]

    # read weights (most recent month per category)
    wt_cats = {}
    for row in ws_weights.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        vals = [v for v in row[3:] if isinstance(v, (int, float))]
        if vals:
            wt_cats[cat] = vals[-1]
    wt_src = list(wt_cats.keys())

    for _hdr, first, last, block in SECTIONS:
        var = variations[block]
        src_cats = list(var.keys())

        for r in range(first, last + 1):
            cat = ws_tabela.cell(r, 2).value
            if cat is None:
                continue

            # weight
            wk = match_name(cat, wt_src)
            if wk:
                ws_tabela.cell(r, 3).value         = wt_cats[wk]
                ws_tabela.cell(r, 3).number_format = NUM_FMT

            # variation values
            sk = match_name(cat, src_cats)
            if not sk:
                continue
            data = var[sk]

            # 6 months (cols D-I)
            for i, c in enumerate(DATE_COLS):
                v = data.get(c)
                cell = ws_tabela.cell(r, 4 + i)
                cell.value         = v if isinstance(v, (int, float)) else None
                cell.number_format = NUM_FMT

            # historical average (col J)
            all_v = [v for v in data.values() if isinstance(v, (int, float))]
            havg  = sum(all_v) / len(all_v) if all_v else None
            ws_tabela.cell(r, 10).value         = havg
            ws_tabela.cell(r, 10).number_format = NUM_FMT

            # distance from average (col K)
            latest = data.get(last_c)
            if isinstance(latest, (int, float)) and isinstance(havg, (int, float)):
                dist = latest - havg
                ws_tabela.cell(r, 11).value         = dist if dist != 0 else None
                ws_tabela.cell(r, 11).number_format = NUM_FMT
            else:
                ws_tabela.cell(r, 11).value = None


# ---------------------------------------------------------------------------
# Step 5 – apply per-row (per-category) std-dev colors
# ---------------------------------------------------------------------------

BLOCK_ROWS = [
    (4,   43,  "MoM"),
    (46,  85,  "MM3MA"),
    (88,  127, "MM6MA"),
    (130, 169, "YoY"),
]


def _stdev_per_cat(var_block):
    """Returns {cat: stdev_of_full_historical_series}."""
    result = {}
    for cat, d in var_block.items():
        vals = [v for v in d.values() if isinstance(v, (int, float))]
        if len(vals) >= 2:
            result[cat] = statistics.stdev(vals)
    return result


def apply_colors(ws_tabela, variations):
    """
    Color scale per category: intensity = min(1.0, |dist| / (2 * stdev_of_that_row's_history)).
    variations = {"MoM": {cat: {col: val}}, ...} from compute_* functions.
    """
    for first, last, block_name in BLOCK_ROWS:
        sd_lookup = _stdev_per_cat(variations[block_name])
        sd_src    = list(sd_lookup.keys())

        for r in range(first, last + 1):
            cat  = ws_tabela.cell(r, 2).value
            dist = ws_tabela.cell(r, 11).value
            cell = ws_tabela.cell(r, 11)

            if not isinstance(dist, (int, float)) or dist == 0:
                cell.fill = PatternFill(fill_type=None)
                continue

            sk = match_name(cat, sd_src)
            if sk is None:
                cell.fill = PatternFill(fill_type=None)
                continue

            cap = 2.0 * sd_lookup[sk]
            if cap < 1e-9:
                cell.fill = PatternFill(fill_type=None)
                continue

            intensity = min(1.0, abs(dist) / cap)
            if dist > 0:
                g = b = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FFFF{g:02X}{b:02X}")
            else:
                rg = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FF{rg:02X}{rg:02X}FF")


# ---------------------------------------------------------------------------
# Step 6 – generate HTML
# ---------------------------------------------------------------------------

SECTION_LABELS = {
    "MoM":   "MoM – Month over Month (%)",
    "MM3MA": "MM3MA – 3-Month Moving Average of MoM (%)",
    "MM6MA": "MM6MA – 6-Month Moving Average of MoM (%)",
    "YoY":   "YoY – Year over Year (%)",
}


def _argb_to_css(argb):
    """FFRRGGBB → rgba(r,g,b,1)"""
    if not argb or len(argb) != 8 or argb == "00000000":
        return ""
    r = int(argb[2:4], 16)
    g = int(argb[4:6], 16)
    b = int(argb[6:8], 16)
    return f"background-color:rgb({r},{g},{b})"


def generate_html(ws_tabela, out_path, latest_label, date_labels):
    """
    date_labels: list of 6 strings [newest, ..., oldest] computed from SOURCE_XLS
                 row 5 — used directly instead of reading Tabela row 3 (which may
                 contain formula strings that openpyxl cannot evaluate).
    """
    html_parts = [f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>US CPI Dashboard – {latest_label}</title>
<style>
  body  {{ font-family: Arial, sans-serif; font-size: 11px; margin: 20px; background: #f9f9f9; }}
  h1    {{ font-size: 16px; color: #2c3e50; margin-bottom: 4px; }}
  h2    {{ font-size: 13px; color: #2c3e50; margin: 24px 0 6px; border-bottom: 2px solid #c00000;
           padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 8px; background: white;
           box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
  th    {{ background: #2c3e50; color: white; padding: 6px 8px; text-align: center;
           font-weight: bold; white-space: nowrap; }}
  th.cat{{ text-align: left; }}
  td    {{ padding: 4px 8px; border: 1px solid #ddd; text-align: right; white-space: nowrap; }}
  td.cat{{ text-align: left; min-width: 200px; max-width: 280px; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  tr:hover {{ background: #f0f0f0 !important; }}
  .dist {{ font-weight: bold; }}
  p.note{{ font-size: 10px; color: #666; }}
</style>
</head>
<body>
<h1>US CPI-U Analysis — {latest_label}</h1>
<p class="note">Source: BLS Public Data API v2. Colors: red = above historical average,
blue = below. Intensity scale capped at ±2σ per category historical series.</p>
"""]

    for block, first_row in [("MoM", 4), ("MM3MA", 46), ("MM6MA", 88), ("YoY", 130)]:
        last_row = first_row + 39

        html_parts.append(f"<h2>{SECTION_LABELS[block]}</h2>\n<table>\n<thead><tr>")
        html_parts.append('<th class="cat">Category</th>')
        html_parts.append("<th>Weight</th>")
        for lbl in date_labels:
            html_parts.append(f"<th>{lbl}</th>")
        html_parts.append("<th>Hist. Avg</th>")
        html_parts.append("<th>Dist. from Avg</th>")
        html_parts.append("</tr></thead>\n<tbody>")

        for r in range(first_row, last_row + 1):
            cat  = ws_tabela.cell(r, 2).value
            if cat is None:
                continue
            peso = ws_tabela.cell(r, 3).value
            vals = [ws_tabela.cell(r, 4 + i).value for i in range(6)]
            havg = ws_tabela.cell(r, 10).value
            dist = ws_tabela.cell(r, 11).value

            try:
                argb = ws_tabela.cell(r, 11).fill.fgColor.rgb
            except Exception:
                argb = None
            bg_style = _argb_to_css(argb) if argb else ""

            def fmt(v):
                return f"{v:.2f}" if isinstance(v, (int, float)) else ""

            html_parts.append("<tr>")
            html_parts.append(f'<td class="cat">{cat}</td>')
            html_parts.append(f"<td>{fmt(peso)}</td>")
            for v in vals:
                html_parts.append(f"<td>{fmt(v)}</td>")
            html_parts.append(f"<td>{fmt(havg)}</td>")
            dist_style = f' style="{bg_style}"' if bg_style else ""
            html_parts.append(f'<td class="dist"{dist_style}>{fmt(dist)}</td>')
            html_parts.append("</tr>")

        html_parts.append("</tbody></table>\n")

    html_parts.append("</body>\n</html>\n")
    out_path.write_text("".join(html_parts), encoding="utf-8")
    print(f"HTML saved: {out_path}")


# ---------------------------------------------------------------------------
# Step 7 – git commit + push
# ---------------------------------------------------------------------------

def git_push(latest_label):
    cmds = [
        ["git", "add", "cpi_table.html", "CLAUDE.md"],
        ["git", "commit", "-m", f"CPI update: {latest_label}"],
        ["git", "push", "origin", "master"],
    ]
    for cmd in cmds:
        r = subprocess.run(cmd, cwd=str(REPO_DIR))
        if r.returncode != 0:
            print(f"  git command failed: {' '.join(cmd)}")
            break
    else:
        print("Pushed to GitHub.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    rebuild_source()

    print("=== Loading raw data ===")
    wb_src     = load_workbook(str(SOURCE_XLS), data_only=True)
    ws_raw     = wb_src["US_CPI"]
    ws_wts_src = wb_src["US_CPI_Weights"]

    raw    = load_raw(ws_raw)
    lc     = last_col(raw)
    latest_label = _col_to_label(lc, ws_raw)
    print(f"Latest month: {latest_label} (col {lc})")

    # date labels for HTML: 6 months newest-first, from SOURCE row 5
    date_labels = [_col_to_label(lc - i, ws_raw) for i in range(6)]

    print("=== Computing Python variations (fallback for uncached new month) ===")
    mom   = compute_mom(raw)
    mm3ma = compute_mma(mom, 3)
    mm6ma = compute_mma(mom, 6)
    yoy   = compute_yoy(raw)
    python_variations = {"MoM": mom, "MM3MA": mm3ma, "MM6MA": mm6ma, "YoY": yoy}

    print("=== Refreshing FINAL.xlsx formula cache (Excel recalculation) ===")
    _excel_recalculate(FINAL_XLS)

    print("=== Reading variation blocks from FINAL.xlsx (Excel-cached values) ===")
    wb_do = load_workbook(str(FINAL_XLS), data_only=True)
    ws_do = wb_do["US_CPI"]
    excel_variations = {}
    for block, (r0, r1) in VARIATION_READ_BLOCKS.items():
        excel_variations[block] = read_variation_block(ws_do, r0, r1, lc)
        print(f"  {block}: {len(excel_variations[block])} categories (rows {r0}-{r1})")
    del wb_do

    variations = _merge_variations(python_variations, excel_variations)

    print("=== Updating FINAL.xlsx ===")
    wb_final     = load_workbook(str(FINAL_XLS))
    ws_tabela    = wb_final["Tabela"]
    ws_final_raw = wb_final["US_CPI"]
    ws_weights   = wb_final["US_CPI_Weights"]

    # 1. Extend raw data sheets with new month column(s)
    print("--- Appending new month to raw sheets ---")
    formula_lc, new_formula_cols = copy_new_months_to_final(ws_raw, ws_wts_src, ws_final_raw, ws_weights)

    # 2. Update only D3 in Tabela (E3:I3 are formula-driven and update in Excel)
    ws_tabela.cell(3, 4).value         = _label_to_date(latest_label)
    ws_tabela.cell(3, 4).number_format = "DD/MM/YYYY"

    # 3. Fill Tabela data rows and colors
    fill_tabela(ws_tabela, ws_weights, variations, lc)
    apply_colors(ws_tabela, variations)

    wb_final.save(str(FINAL_XLS))
    print(f"Saved: {FINAL_XLS}")

    print("=== Extending formula blocks and refreshing cache (Excel COM) ===")
    _extend_and_recalculate(FINAL_XLS, formula_lc, new_formula_cols)

    print("=== Generating HTML ===")
    wb2 = load_workbook(str(FINAL_XLS))
    generate_html(wb2["Tabela"], HTML_OUT, latest_label, date_labels)

    print("=== Git push ===")
    git_push(latest_label)

    print(f"\nDone. CPI updated through {latest_label}.")


if __name__ == "__main__":
    main()
