#!/usr/bin/env python3
"""
Monthly CPI update script.

Run after BLS publishes new CPI data. Workflow:
  1. Re-runs build_us_cpi.py to fetch the latest raw index data from BLS API.
  2. Appends the new month column to US_CPI and US_CPI_Weights sheets in FINAL.xlsx
     (extends row 5 date headers + row 6+ data — never deletes existing dates/data).
  3. Writes the new month label to Tabela cell D3 only; E3:I3 update via their formulas.
  4. Computes MoM / MM3MA / MM6MA / YoY in Python and fills the Tabela data rows.
  5. Generates cpi_table.html for GitHub Pages.
  6. Commits and pushes to GitHub.

Usage:
    cd C:\\Users\\rodri\\us-cpi
    python update_cpi.py
"""

import os, sys, subprocess, statistics
from pathlib import Path
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_DIR   = Path(__file__).parent.resolve()
SOURCE_XLS = REPO_DIR / "US_CPI.xlsx"          # generated by build_us_cpi.py
FINAL_XLS  = Path(r"C:\Users\rodri\CPI\US_CPI_FINAL.xlsx")
HTML_OUT   = REPO_DIR / "cpi_table.html"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def match_name(target, source_cats):
    """Prefix-match category names, returning shortest candidate."""
    t = target.strip().lower()
    for c in source_cats:
        if c.strip().lower() == t:
            return c
    candidates = [c for c in source_cats if c.strip().lower().startswith(t)]
    return min(candidates, key=len) if candidates else None


def _col_to_label(col_idx, ws_raw):
    """Return the Mon-YY header label for a 1-indexed column."""
    v = ws_raw.cell(5, col_idx).value
    return v if v else f"col{col_idx}"


def _last_date_col(ws):
    """Find rightmost column in row 5 that has a non-None value."""
    for c in range(ws.max_column, 3, -1):
        if ws.cell(5, c).value is not None:
            return c
    return 3


def _build_cat_to_row(ws, min_row=6, cat_col=3):
    """Map category name → row number in ws (exact match)."""
    result = {}
    for r in range(min_row, ws.max_row + 1):
        cat = ws.cell(r, cat_col).value
        if cat is not None:
            result[str(cat).strip()] = r
    return result


# ---------------------------------------------------------------------------
# Step 1 – fetch fresh raw data
# ---------------------------------------------------------------------------

def rebuild_source():
    print("=== Running build_us_cpi.py ===")
    result = subprocess.run(
        [sys.executable, str(REPO_DIR / "build_us_cpi.py")],
        cwd=str(REPO_DIR)
    )
    if result.returncode != 0:
        print("ERROR: build_us_cpi.py failed.")
        sys.exit(1)
    print("build_us_cpi.py done.\n")


# ---------------------------------------------------------------------------
# Step 2 – append new month columns to FINAL.xlsx raw sheets
# ---------------------------------------------------------------------------

def copy_new_months_to_final(ws_src_raw, ws_src_wts, ws_final_raw, ws_final_wts):
    """
    Appends any new month columns from SOURCE into FINAL's US_CPI and
    US_CPI_Weights sheets. Never overwrites existing data — only extends.

    Row 5  = date headers (extended for each new month)
    Rows 6+ = index / weight values (matched by category name in col 3)
    """
    final_lc = _last_date_col(ws_final_raw)
    src_lc   = _last_date_col(ws_src_raw)

    if src_lc <= final_lc:
        print(f"  FINAL raw data already current (last col = {final_lc})")
        return

    new_cols = list(range(final_lc + 1, src_lc + 1))
    print(f"  Appending {len(new_cols)} new month(s) to FINAL: col {new_cols[0]}..{new_cols[-1]}")

    # extend date headers in row 5
    for c in new_cols:
        ws_final_raw.cell(5, c).value = ws_src_raw.cell(5, c).value
        ws_final_wts.cell(5, c).value = (ws_src_wts.cell(5, c).value
                                          or ws_src_raw.cell(5, c).value)

    # append index values (US_CPI sheet), matched by category name
    final_rows = _build_cat_to_row(ws_final_raw)
    for r_src in range(6, ws_src_raw.max_row + 1):
        cat = ws_src_raw.cell(r_src, 3).value
        if cat is None:
            continue
        r_fin = final_rows.get(str(cat).strip())
        if r_fin is None:
            continue
        for c in new_cols:
            ws_final_raw.cell(r_fin, c).value = ws_src_raw.cell(r_src, c).value

    # append weight values (US_CPI_Weights sheet)
    final_wt_rows = _build_cat_to_row(ws_final_wts)
    for r_src in range(6, ws_src_wts.max_row + 1):
        cat = ws_src_wts.cell(r_src, 3).value
        if cat is None:
            continue
        r_fin = final_wt_rows.get(str(cat).strip())
        if r_fin is None:
            continue
        for c in new_cols:
            ws_final_wts.cell(r_fin, c).value = ws_src_wts.cell(r_src, c).value


# ---------------------------------------------------------------------------
# Step 3 – compute variations from raw index data
# ---------------------------------------------------------------------------

def load_raw(ws_raw):
    """
    Returns raw[cat_name] = {col_idx(1-based): float}.
    Cols 4+ = months; row 5 = date headers; rows 6+ = categories.
    """
    raw = {}
    for row in ws_raw.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        entry = {}
        for i, v in enumerate(row[3:], start=4):
            if isinstance(v, (int, float)):
                entry[i] = v
        if entry:
            raw[cat] = entry
    return raw


def compute_mom(raw):
    mom = {}
    for cat, cols_d in raw.items():
        cols = sorted(cols_d.keys())
        m = {}
        for i in range(1, len(cols)):
            c, p = cols[i], cols[i - 1]
            cur, prv = cols_d[c], cols_d[p]
            if prv and prv != 0:
                m[c] = (cur / prv - 1) * 100
        mom[cat] = m
    return mom


def compute_mma(mom, window):
    result = {}
    for cat, m in mom.items():
        cols = sorted(m.keys())
        r = {}
        for i in range(window - 1, len(cols)):
            vals = [m[cols[i - j]] for j in range(window)]
            if all(isinstance(v, float) for v in vals):
                r[cols[i]] = sum(vals) / window
        result[cat] = r
    return result


def compute_yoy(raw):
    yoy = {}
    for cat, cols_d in raw.items():
        y = {}
        for c, cur in cols_d.items():
            prv_c = c - 12
            if prv_c in cols_d:
                prv = cols_d[prv_c]
                if prv and prv != 0:
                    y[c] = (cur / prv - 1) * 100
        yoy[cat] = y
    return yoy


def last_col(raw):
    return max(max(d.keys()) for d in raw.values() if d)


# ---------------------------------------------------------------------------
# Step 4 – fill Tabela sheet
# ---------------------------------------------------------------------------

NUM_FMT = "0.00"

SECTIONS = [
    (3,   4,   43,  "MoM"),
    (45,  46,  85,  "MM3MA"),
    (87,  88,  127, "MM6MA"),
    (129, 130, 169, "YoY"),
]


def fill_tabela(ws_tabela, ws_weights, variations, last_c):
    """
    variations = {"MoM": {cat: {col: val}}, "MM3MA": ..., ...}
    last_c     = 1-based column index of the most recent month.

    Writes only data cells (cols C-K in rows 4-169). Header rows and month
    label cells in row 3 are NOT touched here — D3 is written in main().
    """
    DATE_COLS = [last_c - i for i in range(6)]

    # read weights (most recent month per category)
    wt_cats = {}
    for row in ws_weights.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        vals = [v for v in row[3:] if isinstance(v, (int, float))]
        if vals:
            wt_cats[cat] = vals[-1]
    wt_src = list(wt_cats.keys())

    for _hdr, first, last, block in SECTIONS:
        var = variations[block]
        src_cats = list(var.keys())

        for r in range(first, last + 1):
            cat = ws_tabela.cell(r, 2).value
            if cat is None:
                continue

            # weight
            wk = match_name(cat, wt_src)
            if wk:
                ws_tabela.cell(r, 3).value         = wt_cats[wk]
                ws_tabela.cell(r, 3).number_format = NUM_FMT

            # variation values
            sk = match_name(cat, src_cats)
            if not sk:
                continue
            data = var[sk]

            # 6 months (cols D-I)
            for i, c in enumerate(DATE_COLS):
                v = data.get(c)
                cell = ws_tabela.cell(r, 4 + i)
                cell.value         = v if isinstance(v, (int, float)) else None
                cell.number_format = NUM_FMT

            # historical average (col J)
            all_v = [v for v in data.values() if isinstance(v, (int, float))]
            havg  = sum(all_v) / len(all_v) if all_v else None
            ws_tabela.cell(r, 10).value         = havg
            ws_tabela.cell(r, 10).number_format = NUM_FMT

            # distance from average (col K)
            latest = data.get(last_c)
            if isinstance(latest, (int, float)) and isinstance(havg, (int, float)):
                dist = latest - havg
                ws_tabela.cell(r, 11).value         = dist if dist != 0 else None
                ws_tabela.cell(r, 11).number_format = NUM_FMT
            else:
                ws_tabela.cell(r, 11).value = None


# ---------------------------------------------------------------------------
# Step 5 – apply per-row (per-category) std-dev colors
# ---------------------------------------------------------------------------

BLOCK_ROWS = [
    (4,   43,  "MoM"),
    (46,  85,  "MM3MA"),
    (88,  127, "MM6MA"),
    (130, 169, "YoY"),
]


def _stdev_per_cat(var_block):
    """Returns {cat: stdev_of_full_historical_series}."""
    result = {}
    for cat, d in var_block.items():
        vals = [v for v in d.values() if isinstance(v, (int, float))]
        if len(vals) >= 2:
            result[cat] = statistics.stdev(vals)
    return result


def apply_colors(ws_tabela, variations):
    """
    Color scale per category: intensity = min(1.0, |dist| / (2 * stdev_of_that_row's_history)).
    variations = {"MoM": {cat: {col: val}}, ...} from compute_* functions.
    """
    for first, last, block_name in BLOCK_ROWS:
        sd_lookup = _stdev_per_cat(variations[block_name])
        sd_src    = list(sd_lookup.keys())

        for r in range(first, last + 1):
            cat  = ws_tabela.cell(r, 2).value
            dist = ws_tabela.cell(r, 11).value
            cell = ws_tabela.cell(r, 11)

            if not isinstance(dist, (int, float)) or dist == 0:
                cell.fill = PatternFill(fill_type=None)
                continue

            sk = match_name(cat, sd_src)
            if sk is None:
                cell.fill = PatternFill(fill_type=None)
                continue

            cap = 2.0 * sd_lookup[sk]
            if cap < 1e-9:
                cell.fill = PatternFill(fill_type=None)
                continue

            intensity = min(1.0, abs(dist) / cap)
            if dist > 0:
                g = b = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FFFF{g:02X}{b:02X}")
            else:
                rg = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FF{rg:02X}{rg:02X}FF")


# ---------------------------------------------------------------------------
# Step 6 – generate HTML
# ---------------------------------------------------------------------------

SECTION_LABELS = {
    "MoM":   "MoM – Month over Month (%)",
    "MM3MA": "MM3MA – 3-Month Moving Average of MoM (%)",
    "MM6MA": "MM6MA – 6-Month Moving Average of MoM (%)",
    "YoY":   "YoY – Year over Year (%)",
}


def _argb_to_css(argb):
    """FFRRGGBB → rgba(r,g,b,1)"""
    if not argb or len(argb) != 8 or argb == "00000000":
        return ""
    r = int(argb[2:4], 16)
    g = int(argb[4:6], 16)
    b = int(argb[6:8], 16)
    return f"background-color:rgb({r},{g},{b})"


def generate_html(ws_tabela, out_path, latest_label, date_labels):
    """
    date_labels: list of 6 strings [newest, ..., oldest] computed from SOURCE_XLS
                 row 5 — used directly instead of reading Tabela row 3 (which may
                 contain formula strings that openpyxl cannot evaluate).
    """
    html_parts = [f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>US CPI Dashboard – {latest_label}</title>
<style>
  body  {{ font-family: Arial, sans-serif; font-size: 11px; margin: 20px; background: #f9f9f9; }}
  h1    {{ font-size: 16px; color: #2c3e50; margin-bottom: 4px; }}
  h2    {{ font-size: 13px; color: #2c3e50; margin: 24px 0 6px; border-bottom: 2px solid #c00000;
           padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 8px; background: white;
           box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
  th    {{ background: #2c3e50; color: white; padding: 6px 8px; text-align: center;
           font-weight: bold; white-space: nowrap; }}
  th.cat{{ text-align: left; }}
  td    {{ padding: 4px 8px; border: 1px solid #ddd; text-align: right; white-space: nowrap; }}
  td.cat{{ text-align: left; min-width: 200px; max-width: 280px; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  tr:hover {{ background: #f0f0f0 !important; }}
  .dist {{ font-weight: bold; }}
  p.note{{ font-size: 10px; color: #666; }}
</style>
</head>
<body>
<h1>US CPI-U Analysis — {latest_label}</h1>
<p class="note">Source: BLS Public Data API v2. Colors: red = above historical average,
blue = below. Intensity scale capped at ±2σ per category historical series.</p>
"""]

    for block, first_row in [("MoM", 4), ("MM3MA", 46), ("MM6MA", 88), ("YoY", 130)]:
        last_row = first_row + 39

        html_parts.append(f"<h2>{SECTION_LABELS[block]}</h2>\n<table>\n<thead><tr>")
        html_parts.append('<th class="cat">Category</th>')
        html_parts.append("<th>Weight</th>")
        for lbl in date_labels:
            html_parts.append(f"<th>{lbl}</th>")
        html_parts.append("<th>Hist. Avg</th>")
        html_parts.append("<th>Dist. from Avg</th>")
        html_parts.append("</tr></thead>\n<tbody>")

        for r in range(first_row, last_row + 1):
            cat  = ws_tabela.cell(r, 2).value
            if cat is None:
                continue
            peso = ws_tabela.cell(r, 3).value
            vals = [ws_tabela.cell(r, 4 + i).value for i in range(6)]
            havg = ws_tabela.cell(r, 10).value
            dist = ws_tabela.cell(r, 11).value

            try:
                argb = ws_tabela.cell(r, 11).fill.fgColor.rgb
            except Exception:
                argb = None
            bg_style = _argb_to_css(argb) if argb else ""

            def fmt(v):
                return f"{v:.2f}" if isinstance(v, (int, float)) else ""

            html_parts.append("<tr>")
            html_parts.append(f'<td class="cat">{cat}</td>')
            html_parts.append(f"<td>{fmt(peso)}</td>")
            for v in vals:
                html_parts.append(f"<td>{fmt(v)}</td>")
            html_parts.append(f"<td>{fmt(havg)}</td>")
            dist_style = f' style="{bg_style}"' if bg_style else ""
            html_parts.append(f'<td class="dist"{dist_style}>{fmt(dist)}</td>')
            html_parts.append("</tr>")

        html_parts.append("</tbody></table>\n")

    html_parts.append("</body>\n</html>\n")
    out_path.write_text("".join(html_parts), encoding="utf-8")
    print(f"HTML saved: {out_path}")


# ---------------------------------------------------------------------------
# Step 7 – git commit + push
# ---------------------------------------------------------------------------

def git_push(latest_label):
    cmds = [
        ["git", "add", "cpi_table.html", "CLAUDE.md"],
        ["git", "commit", "-m", f"CPI update: {latest_label}"],
        ["git", "push", "origin", "master"],
    ]
    for cmd in cmds:
        r = subprocess.run(cmd, cwd=str(REPO_DIR))
        if r.returncode != 0:
            print(f"  git command failed: {' '.join(cmd)}")
            break
    else:
        print("Pushed to GitHub.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    rebuild_source()

    print("=== Loading raw data ===")
    wb_src     = load_workbook(str(SOURCE_XLS), data_only=True)
    ws_raw     = wb_src["US_CPI"]
    ws_wts_src = wb_src["US_CPI_Weights"]

    raw    = load_raw(ws_raw)
    lc     = last_col(raw)
    latest_label = _col_to_label(lc, ws_raw)
    print(f"Latest month: {latest_label} (col {lc})")

    # date labels for HTML: 6 months newest-first, from SOURCE row 5
    date_labels = [_col_to_label(lc - i, ws_raw) for i in range(6)]

    print("=== Computing variations ===")
    mom   = compute_mom(raw)
    mm3ma = compute_mma(mom, 3)
    mm6ma = compute_mma(mom, 6)
    yoy   = compute_yoy(raw)
    variations = {"MoM": mom, "MM3MA": mm3ma, "MM6MA": mm6ma, "YoY": yoy}

    print("=== Updating FINAL.xlsx ===")
    wb_final     = load_workbook(str(FINAL_XLS))
    ws_tabela    = wb_final["Tabela"]
    ws_final_raw = wb_final["US_CPI"]
    ws_weights   = wb_final["US_CPI_Weights"]

    # 1. Extend raw data sheets with new month column(s)
    print("--- Appending new month to raw sheets ---")
    copy_new_months_to_final(ws_raw, ws_wts_src, ws_final_raw, ws_weights)

    # 2. Update only D3 in Tabela (E3:I3 are formula-driven and update in Excel)
    ws_tabela.cell(3, 4).value = latest_label

    # 3. Fill Tabela data rows and colors
    fill_tabela(ws_tabela, ws_weights, variations, lc)
    apply_colors(ws_tabela, variations)

    wb_final.save(str(FINAL_XLS))
    print(f"Saved: {FINAL_XLS}")

    print("=== Generating HTML ===")
    wb2 = load_workbook(str(FINAL_XLS))
    generate_html(wb2["Tabela"], HTML_OUT, latest_label, date_labels)

    print("=== Git push ===")
    git_push(latest_label)

    print(f"\nDone. CPI updated through {latest_label}.")


if __name__ == "__main__":
    main()
