#!/usr/bin/env python3
"""
Monthly CPI update script.

Run after BLS publishes new CPI data. Workflow:
  1. Re-runs build_us_cpi.py to fetch the latest raw index data from BLS API.
  2. Computes MoM / MM3MA / MM6MA / YoY variations in Python from raw data.
  3. Updates the Tabela sheet in US_CPI_FINAL.xlsx with new values and colors.
  4. Generates cpi_table.html for GitHub Pages.
  5. Commits and pushes to GitHub.

Usage:
    cd C:\\Users\\rodri\\us-cpi
    python update_cpi.py
"""

import os, sys, subprocess, statistics
from pathlib import Path
from openpyxl import load_workbook
from openpyxl.styles import PatternFill

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_DIR   = Path(__file__).parent.resolve()
SOURCE_XLS = REPO_DIR / "US_CPI.xlsx"          # generated by build_us_cpi.py
FINAL_XLS  = Path(r"C:\Users\rodri\CPI\US_CPI_FINAL.xlsx")
HTML_OUT   = REPO_DIR / "cpi_table.html"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def match_name(target, source_cats):
    """Prefix-match category names, returning shortest candidate."""
    t = target.strip().lower()
    for c in source_cats:
        if c.strip().lower() == t:
            return c
    candidates = [c for c in source_cats if c.strip().lower().startswith(t)]
    return min(candidates, key=len) if candidates else None


def _col_to_label(col_idx, ws_raw):
    """Return the Mon-YY header label for a 1-indexed column."""
    v = ws_raw.cell(5, col_idx).value
    return v if v else f"col{col_idx}"


# ---------------------------------------------------------------------------
# Step 1 – fetch fresh raw data
# ---------------------------------------------------------------------------

def rebuild_source():
    print("=== Running build_us_cpi.py ===")
    result = subprocess.run(
        [sys.executable, str(REPO_DIR / "build_us_cpi.py")],
        cwd=str(REPO_DIR)
    )
    if result.returncode != 0:
        print("ERROR: build_us_cpi.py failed.")
        sys.exit(1)
    print("build_us_cpi.py done.\n")


# ---------------------------------------------------------------------------
# Step 2 – compute variations from raw index data
# ---------------------------------------------------------------------------

def load_raw(ws_raw):
    """
    Returns raw[cat_name] = {col_idx(1-based): float}.
    Cols 4+ = months; row 5 = date headers; rows 6+ = categories.
    """
    raw = {}
    for row in ws_raw.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        entry = {}
        for i, v in enumerate(row[3:], start=4):
            if isinstance(v, (int, float)):
                entry[i] = v
        if entry:
            raw[cat] = entry
    return raw


def compute_mom(raw):
    mom = {}
    for cat, cols_d in raw.items():
        cols = sorted(cols_d.keys())
        m = {}
        for i in range(1, len(cols)):
            c, p = cols[i], cols[i - 1]
            cur, prv = cols_d[c], cols_d[p]
            if prv and prv != 0:
                m[c] = (cur / prv - 1) * 100
        mom[cat] = m
    return mom


def compute_mma(mom, window):
    result = {}
    for cat, m in mom.items():
        cols = sorted(m.keys())
        r = {}
        for i in range(window - 1, len(cols)):
            vals = [m[cols[i - j]] for j in range(window)]
            if all(isinstance(v, float) for v in vals):
                r[cols[i]] = sum(vals) / window
        result[cat] = r
    return result


def compute_yoy(raw):
    yoy = {}
    for cat, cols_d in raw.items():
        y = {}
        for c, cur in cols_d.items():
            prv_c = c - 12
            if prv_c in cols_d:
                prv = cols_d[prv_c]
                if prv and prv != 0:
                    y[c] = (cur / prv - 1) * 100
        yoy[cat] = y
    return yoy


def last_col(raw):
    return max(max(d.keys()) for d in raw.values() if d)


# ---------------------------------------------------------------------------
# Step 3 – fill Tabela sheet
# ---------------------------------------------------------------------------

NUM_FMT = "0.00"

SECTIONS = [
    (3,   4,   43,  "MoM"),
    (45,  46,  85,  "MM3MA"),
    (87,  88,  127, "MM6MA"),
    (129, 130, 169, "YoY"),
]


def fill_tabela(ws_tabela, ws_weights, variations, last_c):
    """
    variations = {"MoM": {cat: {col: val}}, "MM3MA": ..., ...}
    last_c     = 1-based column index of the most recent month.
    """
    DATE_COLS = [last_c - i for i in range(6)]

    # --- read weights (most recent month per category) ---
    wt_cats = {}
    for row in ws_weights.iter_rows(min_row=6, values_only=True):
        cat = row[2]
        if cat is None:
            continue
        vals = [v for v in row[3:] if isinstance(v, (int, float))]
        if vals:
            wt_cats[cat] = vals[-1]
    wt_src = list(wt_cats.keys())

    for _hdr, first, last, block in SECTIONS:
        var = variations[block]
        src_cats = list(var.keys())

        for r in range(first, last + 1):
            cat = ws_tabela.cell(r, 2).value
            if cat is None:
                continue

            # weight
            wk = match_name(cat, wt_src)
            if wk:
                ws_tabela.cell(r, 3).value         = wt_cats[wk]
                ws_tabela.cell(r, 3).number_format = NUM_FMT

            # variation values
            sk = match_name(cat, src_cats)
            if not sk:
                continue
            data = var[sk]

            # 6 months
            for i, c in enumerate(DATE_COLS):
                v = data.get(c)
                cell = ws_tabela.cell(r, 4 + i)
                cell.value         = v if isinstance(v, (int, float)) else None
                cell.number_format = NUM_FMT

            # historical average
            all_v = [v for v in data.values() if isinstance(v, (int, float))]
            havg  = sum(all_v) / len(all_v) if all_v else None
            ws_tabela.cell(r, 10).value         = havg
            ws_tabela.cell(r, 10).number_format = NUM_FMT

            # distance
            latest = data.get(last_c)
            if isinstance(latest, (int, float)) and isinstance(havg, (int, float)):
                dist = latest - havg
                ws_tabela.cell(r, 11).value         = dist if dist != 0 else None
                ws_tabela.cell(r, 11).number_format = NUM_FMT
            else:
                ws_tabela.cell(r, 11).value = None


# ---------------------------------------------------------------------------
# Step 4 – apply std-dev colors
# ---------------------------------------------------------------------------

COLOR_SECTIONS = [(4, 43), (46, 85), (88, 127), (130, 169)]


def apply_colors(ws_tabela):
    for first, last in COLOR_SECTIONS:
        dists = []
        for r in range(first, last + 1):
            v = ws_tabela.cell(r, 11).value
            if isinstance(v, (int, float)) and v != 0:
                dists.append(v)
        if len(dists) < 2:
            continue
        cap = 2.0 * statistics.stdev(dists)
        if cap < 1e-9:
            continue
        for r in range(first, last + 1):
            v    = ws_tabela.cell(r, 11).value
            cell = ws_tabela.cell(r, 11)
            if not isinstance(v, (int, float)) or v == 0:
                cell.fill = PatternFill(fill_type=None)
                continue
            intensity = min(1.0, abs(v) / cap)
            if v > 0:
                g = b = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FFFF{g:02X}{b:02X}")
            else:
                rg = round(255 * (1.0 - intensity))
                cell.fill = PatternFill("solid", fgColor=f"FF{rg:02X}{rg:02X}FF")


# ---------------------------------------------------------------------------
# Step 5 – generate HTML
# ---------------------------------------------------------------------------

SECTION_LABELS = {
    "MoM":   "MoM – Month over Month (%)",
    "MM3MA": "MM3MA – 3-Month Moving Average of MoM (%)",
    "MM6MA": "MM6MA – 6-Month Moving Average of MoM (%)",
    "YoY":   "YoY – Year over Year (%)",
}


def _cell_style(v):
    if not isinstance(v, (int, float)) or v == 0:
        return ""
    # recompute intensity (approximate, for HTML – exact would need per-section cap)
    return ""  # colors will be read from the filled cells


def _argb_to_css(argb):
    """FFRRGGBB → rgba(r,g,b,1)"""
    if not argb or len(argb) != 8 or argb == "00000000":
        return ""
    r = int(argb[2:4], 16)
    g = int(argb[4:6], 16)
    b = int(argb[6:8], 16)
    return f"background-color:rgb({r},{g},{b})"


def generate_html(ws_tabela, out_path, latest_label):
    rows_by_section = {
        "MoM":   list(range(4,  44)),
        "MM3MA": list(range(46, 86)),
        "MM6MA": list(range(88, 128)),
        "YoY":   list(range(130, 170)),
    }
    # read header date labels from row 3 / 45 / 87 / 129 cols D-I
    header_rows = {"MoM": 3, "MM3MA": 45, "MM6MA": 87, "YoY": 129}

    html_parts = [f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>US CPI Dashboard – {latest_label}</title>
<style>
  body  {{ font-family: Arial, sans-serif; font-size: 11px; margin: 20px; background: #f9f9f9; }}
  h1    {{ font-size: 16px; color: #2c3e50; margin-bottom: 4px; }}
  h2    {{ font-size: 13px; color: #2c3e50; margin: 24px 0 6px; border-bottom: 2px solid #c00000;
           padding-bottom: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 8px; background: white;
           box-shadow: 0 1px 3px rgba(0,0,0,.1); }}
  th    {{ background: #2c3e50; color: white; padding: 6px 8px; text-align: center;
           font-weight: bold; white-space: nowrap; }}
  th.cat{{ text-align: left; }}
  td    {{ padding: 4px 8px; border: 1px solid #ddd; text-align: right; white-space: nowrap; }}
  td.cat{{ text-align: left; min-width: 200px; max-width: 280px; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  tr:hover {{ background: #f0f0f0 !important; }}
  .dist {{ font-weight: bold; }}
  p.note{{ font-size: 10px; color: #666; }}
</style>
</head>
<body>
<h1>US CPI-U Analysis — {latest_label}</h1>
<p class="note">Source: BLS Public Data API v2. Colors: red = above historical average,
blue = below. Intensity scale capped at ±2σ per section.</p>
"""]

    for block, first_row in [("MoM", 4), ("MM3MA", 46), ("MM6MA", 88), ("YoY", 130)]:
        last_row = first_row + 39
        hdr_row  = header_rows[block]

        # date labels
        date_labels = [ws_tabela.cell(hdr_row, 4 + i).value or f"M-{i}" for i in range(6)]

        html_parts.append(f"<h2>{SECTION_LABELS[block]}</h2>\n<table>\n<thead><tr>")
        html_parts.append('<th class="cat">Category</th>')
        html_parts.append("<th>Weight</th>")
        for lbl in date_labels:
            html_parts.append(f"<th>{lbl}</th>")
        html_parts.append("<th>Hist. Avg</th>")
        html_parts.append("<th>Dist. from Avg</th>")
        html_parts.append("</tr></thead>\n<tbody>")

        for r in range(first_row, last_row + 1):
            cat  = ws_tabela.cell(r, 2).value
            if cat is None:
                continue
            peso = ws_tabela.cell(r, 3).value
            vals = [ws_tabela.cell(r, 4 + i).value for i in range(6)]
            havg = ws_tabela.cell(r, 10).value
            dist = ws_tabela.cell(r, 11).value

            # color for distance cell
            try:
                argb = ws_tabela.cell(r, 11).fill.fgColor.rgb
            except Exception:
                argb = None
            bg_style = _argb_to_css(argb) if argb else ""

            def fmt(v):
                return f"{v:.2f}" if isinstance(v, (int, float)) else ""

            html_parts.append("<tr>")
            html_parts.append(f'<td class="cat">{cat}</td>')
            html_parts.append(f"<td>{fmt(peso)}</td>")
            for v in vals:
                html_parts.append(f"<td>{fmt(v)}</td>")
            html_parts.append(f"<td>{fmt(havg)}</td>")
            dist_style = f' style="{bg_style}"' if bg_style else ""
            html_parts.append(f'<td class="dist"{dist_style}>{fmt(dist)}</td>')
            html_parts.append("</tr>")

        html_parts.append("</tbody></table>\n")

    html_parts.append("</body>\n</html>\n")
    out_path.write_text("".join(html_parts), encoding="utf-8")
    print(f"HTML saved: {out_path}")


# ---------------------------------------------------------------------------
# Step 6 – git commit + push
# ---------------------------------------------------------------------------

def git_push(latest_label):
    cmds = [
        ["git", "add", "cpi_table.html", "CLAUDE.md"],
        ["git", "commit", "-m", f"CPI update: {latest_label}"],
        ["git", "push", "origin", "master"],
    ]
    for cmd in cmds:
        r = subprocess.run(cmd, cwd=str(REPO_DIR))
        if r.returncode != 0:
            print(f"  git command failed: {' '.join(cmd)}")
            break
    else:
        print("Pushed to GitHub.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    rebuild_source()

    print("=== Loading raw data ===")
    wb_src = load_workbook(str(SOURCE_XLS), data_only=True)
    ws_raw = wb_src["US_CPI"]
    ws_wts = wb_src["US_CPI_Weights"]

    raw    = load_raw(ws_raw)
    lc     = last_col(raw)
    latest_label = _col_to_label(lc, ws_raw)
    print(f"Latest month: {latest_label} (col {lc})")

    print("=== Computing variations ===")
    mom   = compute_mom(raw)
    mm3ma = compute_mma(mom, 3)
    mm6ma = compute_mma(mom, 6)
    yoy   = compute_yoy(raw)
    variations = {"MoM": mom, "MM3MA": mm3ma, "MM6MA": mm6ma, "YoY": yoy}

    print("=== Updating Tabela ===")
    wb_final   = load_workbook(str(FINAL_XLS))
    ws_tabela  = wb_final["Tabela"]
    ws_weights = wb_final["US_CPI_Weights"]

    fill_tabela(ws_tabela, ws_weights, variations, lc)
    apply_colors(ws_tabela)

    wb_final.save(str(FINAL_XLS))
    print(f"Saved: {FINAL_XLS}")

    print("=== Generating HTML ===")
    # reload to get fill colors (just saved)
    wb2 = load_workbook(str(FINAL_XLS))
    generate_html(wb2["Tabela"], HTML_OUT, latest_label)

    print("=== Git push ===")
    git_push(latest_label)

    print(f"\nDone. CPI updated through {latest_label}.")


if __name__ == "__main__":
    main()
